# Generated by Django 5.1.3 on 2024-12-09 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracks')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(default=1, help_text='Track number in album', validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(default=1, verbose_name='release year')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tracks')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.album')),
                ('artists', models.ManyToManyField(to='artists.artist')),
            ],
        ),
    ]
